INSERT INTO tb_user(email) VALUES ('maria@gmail.com');
INSERT INTO tb_user(email) VALUES ('joao@gmail.com');
INSERT INTO tb_user(email) VALUES ('ana@gmail.com');
INSERT INTO tb_user(email) VALUES ('lucia@gmail.com');
INSERT INTO tb_user(email) VALUES ('joaquim@gmail.com');

INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Shingeki no Kyojin: Attack on Titan', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/eHLODQnYO1KM5AjKf54WIf5L6uw.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Boku no Hero: My Hero Academia', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/7uVyf7or5KxQfO2h0OrV1ZZ99WK.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Kiseijuu: Parasyte', 'http://5b0988e595225.cdn.sohucs.com/q_70,c_zoom,w_640/images/20180123/953f4d86686146e7a762b55ff317b371.jpeg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Kimetsu no Yaiba', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/nTvM4mhqNlHIvUkI1gVnW6XP7GG.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Black Clover', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/tQItgCaJVrXhe6CsJZ5qOKpOoRQ.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Fairy Tail', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSv5Y7goCgKmYwfDHU_leQ1fGZOx9n-OUUf8A&usqp=CAU');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'One Punch Man', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/a8BknzvFVK5EZ83rKg1a83iwaj0.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Isekai Shokudou', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/aEyaGYPj97JliAtmedrHJxWEe1w.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Hunter x Hunter (2011)', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/sjyobk8kdUzNlkejRhv68tNRJeB.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Death Note', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/swxUGe55tVS1062PGl5EB9kC31r.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Mirai Nikki', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/Aqtu1PhSilBxWEiQbVjdsXHv1v5.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Ao no Exorcist', 'http://4.bp.blogspot.com/-Fx7tq9-UNvQ/TjCThdLAXDI/AAAAAAAABRg/w5FgGNSyXQE/s1600/ao_no_exorcist_gg_star_driver_ep17_advert1-533x300.png');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Another', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/6qGNb8onKau8LUAPdKSoRHpNc3s.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Meu Amigo Totoro', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/jHo6W1gkDbcFx5gAS8PuJnqXHge.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'A viagem de Chihiro', 'https://www.coxinhanerd.com.br/wp-content/uploads/2020/03/a-viagem-de-chihiro-533x300.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'O Castelo Animado', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/vwBa7djy1oxfxUjc7YtVgGNsjrT.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Nanatsu no Taizai: 7 Pecados Capitais', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/fJ0Jy7NNdqIuYcYNqeK7YJHVLL0.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Blood Lad', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/2JmtUtysPQnSpZTpvlZ1rVsnStm.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Mob Psycho 100', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/aFcv9zeJtSbJHSYUlQCOQYV3Gio.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Assassination Classroom', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/fIOYLPOorKvP4wut9y0edpnWROz.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'The Promised Neverland', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/8RWcKSmCbwsN8porFyTOB5e2cDG.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Mushishi', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/58zQQAMQvCGIWzClAZtOvbuhe1O.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Sword Art Online', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/kNxL3TFgoTyq85mW71PtqbLxWn7.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Dororo', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/6TX5aQHlJKdRZqV9nFPty3dOdfe.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Digimon', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/qZS4qCvgE4BhLiCnQ1ng0Y3gLSw.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Fullmetal Alchemist: Brotherhood', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/A6tMQAo6t6eRFCPhsrShmxZLqFB.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Kami no Tou: Tower of God', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/wObJhaOGVASHTOQpxoPxZi3DE6c.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Jujutsu Kaisen', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/eGYaVtwWInTzAT6HOGyAj1BTqnB.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Beastars', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/2wM5EIOkEdf0wyaCVwdAuxiAzHM.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Ponyo', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/shqLeIkqPAAXM8iT6wVDiXUYz1p.jpg');

INSERT INTO tb_score(movie_id, user_id, value) VALUES (1, 1, 5.0);
INSERT INTO tb_score(movie_id, user_id, value) VALUES (1, 2, 4.0);
INSERT INTO tb_score(movie_id, user_id, value) VALUES (2, 1, 3.0);
INSERT INTO tb_score(movie_id, user_id, value) VALUES (2, 2, 3.0);
INSERT INTO tb_score(movie_id, user_id, value) VALUES (2, 3, 4.0);